# Generated by Django 5.2.7 on 2025-10-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('actor', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('delivery_mode', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
