# Generated by Django 5.2.7 on 2025-10-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='movies.movie')),
            ],
            options={
                'verbose_name': 'movie_profile',
                'verbose_name_plural': 'Movie Profiles',
                'db_table': 'movie_profile',
            },
        ),
    ]
