# Generated by Django 5.2.7 on 2025-10-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='movieprofile',
            table=None,
        ),
    ]
